import os
os.mkdir('../model_trained/andheri')
os.system('python nn_andheri_train.py')
print('done for andheri')
os.mkdir('../model_trained/bandra_east')
os.system('python nn_bandra_east_train.py')
print('done for bandra_east')
os.mkdir('../model_trained/bandra_west')
os.system('python nn_bandra_west_train.py')
print('done for bandra_west')
os.mkdir('../model_trained/borivali_west')
os.system('python nn_borivali_west_train.py')
print('done for borivali_west')
os.mkdir('../model_trained/chembur')
os.system('python nn_chembur_train.py')
print('done for chembur')
os.mkdir('../model_trained/chembur_east')
os.system('python nn_chembur_east_train.py')
print('done for chembur_east')
os.mkdir('../model_trained/colaba')
os.system('python nn_colaba_train.py')
print('done for colaba')
os.mkdir('../model_trained/cst')
os.system('python nn_cst_train.py')
print('done for cst')
os.mkdir('../model_trained/dadar')
os.system('python nn_dadar_train.py')
print('done for dadar')
os.mkdir('../model_trained/ghatkopar')
os.system('python nn_ghatkopar_train.py')
print('done for ghatkopar')
os.mkdir('../model_trained/ghatkopar_east')
os.system('python nn_ghatkopar_east_train.py')
print('done for ghatkopar_east')
os.mkdir('../model_trained/ghatkopar_west')
os.system('python nn_ghatkopar_west_train.py')
print('done for ghatkopar_west')
os.mkdir('../model_trained/goregaon')
os.system('python nn_goregaon_train.py')
print('done for goregaon')
os.mkdir('../model_trained/gowandi')
os.system('python nn_gowandi_train.py')
print('done for gowandi')
os.mkdir('../model_trained/juhu')
os.system('python nn_juhu_train.py')
print('done for juhu')
os.mkdir('../model_trained/kandivali_east')
os.system('python nn_kandivali_east_train.py')
print('done for kandivali_east')
os.mkdir('../model_trained/kandivali_west')
os.system('python nn_kandivali_west_train.py')
print('done for kandivali_west')
os.mkdir('../model_trained/khar')
os.system('python nn_khar_train.py')
print('done for khar')
os.mkdir('../model_trained/khar_west')
os.system('python nn_khar_west_train.py')
print('done for khar_west')
os.mkdir('../model_trained/kurla')
os.system('python nn_kurla_train.py')
print('done for kurla')
os.mkdir('../model_trained/malad')
os.system('python nn_malad_train.py')
print('done for malad')
os.mkdir('../model_trained/mulund')
os.system('python nn_mulund_train.py')
print('done for mulund')
os.mkdir('../model_trained/mulund_east')
os.system('python nn_mulund_east_train.py')
print('done for mulund_east')
os.mkdir('../model_trained/mulund_west')
os.system('python nn_mulund_west_train.py')
print('done for mulund_west')
os.mkdir('../model_trained/mumbai_central')
os.system('python nn_mumbai_central_train.py')
print('done for mumbai_central')
os.mkdir('../model_trained/nagpada')
os.system('python nn_nagpada_train.py')
print('done for nagpada')
os.mkdir('../model_trained/parel')
os.system('python nn_parel_train.py')
print('done for parel')
os.mkdir('../model_trained/sewree')
os.system('python nn_sewree_train.py')
print('done for sewree')
os.mkdir('../model_trained/sion')
os.system('python nn_sion_train.py')
print('done for sion')
os.mkdir('../model_trained/trombay')
os.system('python nn_trombay_train.py')
print('done for trombay')
os.mkdir('../model_trained/vikhroli')
os.system('python nn_vikhroli_train.py')
print('done for vikhroli')
os.mkdir('../model_trained/vikhroli_east')
os.system('python nn_vikhroli_east_train.py')
print('done for vikhroli_east')
os.mkdir('../model_trained/vile_parle')
os.system('python nn_vile_parle_train.py')
print('done for vile_parle')
os.mkdir('../model_trained/worli')
os.system('python nn_worli_train.py')
print('done for worli')
